name: okta_models
description: "Shared data models for client and server."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.7
  build_runner: ^2.4.13
  json_serializable: ^6.11.1

